### ISSUE TITLE
An introduction to using var name = new var(); is missing.

### ISSUE THREAD

**Issue by Frederisk** [dotnet/docs.zh-tw#226]
The explanation for using in code like the following is missing.

    *using* var decryptStream = new MemoryStream();
    *using* var decrypt = new CryptoStream(decryptStream, decryptTransform, CryptoStreamMode.Write);
    decrypt.Write(encryptBytes, 0, encryptBytes.Length);
    var decryptBytes = decryptStream.ToArray();
    var decryptedString = Encoding.UTF8.GetString(decryptBytes, 0, decryptBytes.Length);
    return decryptedString;

I hope it can be added.

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 042902cc-1598-5df1-34cc-caa0fad63e02
* Version Independent ID: e186d0c4-523e-38f7-2cde-d00109ea784b
* Content: [using 陳述式 - C# 參考](https://docs.microsoft.com/zh-tw/dotnet/csharp/language-reference/keywords/using-statement#feedback)
* Content Source: [docs/csharp/language-reference/keywords/using-statement.md](https://github.com/dotnet/docs.zh-tw/blob/live/docs/csharp/language-reference/keywords/using-statement.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #13200](https://github.com/dotnet/docs/issues/13200) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @Frederisk 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/13200

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
